"""empty message

Revision ID: eacc67e48bd4
Revises: 31cb2d758e1b
Create Date: 2021-04-15 16:41:42.473094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eacc67e48bd4'
down_revision = '31cb2d758e1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('make', sa.String(length=25), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.Column('colour', sa.String(length=25), nullable=True),
    sa.Column('year', sa.String(length=4), nullable=True),
    sa.Column('transmission', sa.String(length=25), nullable=True),
    sa.Column('car_type', sa.String(length=25), nullable=True),
    sa.Column('photo', sa.String(length=150), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favourites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favourites')
    op.drop_table('cars')
    # ### end Alembic commands ###
